sources:
  primary:
    kind: git
    worktree: "."
    url: "https://github.com/sofmeright/stagefreight"
    default_branch: "main"

git:
  policy:
    tags:
      stable: "^\\d+\\.\\d+\\.\\d+$"
      prerelease: "^\\d+\\.\\d+\\.\\d+-.+"
    branches:
      main: "^main$"
  narrator:
    link_base: "https://github.com/sofmeright/stagefreight/blob/main"
    badges:
      font: dejavu-sans
      font_size: 11
    files:
      - id: readme
        path: "README.md"
        sections:
          - id: readme.badges
            name: badges
            inline: true
            items:
              - id: badge.release
                badge: release
                color: "#74ecbe"
                output: ".stagefreight/badges/release.svg"
                link: "https://github.com/sofmeright/stagefreight/releases"
              - id: badge.build
                badge: build
                value: "{env:BUILD_STATUS}"
                color: auto
                font: monofur
                output: ".stagefreight/badges/build.svg"
                link: "https://github.com/sofmeright/stagefreight/actions"
              - id: badge.license
                badge: license
                value: "AGPL-3.0+"
                color: "#310937"
                font: monofur
                output: ".stagefreight/badges/license.svg"
                link: LICENSE
              - id: badge.updated
                badge: updated
                value: "{env:BUILD_DATE}"
                color: "#236144"
                output: ".stagefreight/badges/updated.svg"
              - id: shield.pulls
                shield: docker/pulls/prplanit/stagefreight
                link: "https://hub.docker.com/r/prplanit/stagefreight"
      - id: component-docs
        path: "docs/Component.md"
        sections:
          - id: component-docs.inputs
            name: component
            items:
              - component: "templates/stagefreight.yml"

docker:
  readme:
    description: "Declarative CI/CD CLI — detect, build, scan, and release container images from one manifest"
    file: "README.md"

  platforms: [linux/amd64]

  registries:
    # ── Docker Hub: stable releases ─────────────────────────────────
    # Full rolling tag set. Renovate picks up {base} for auto-updates.
    # Only clean semver tags (no prerelease suffix).
    - url: docker.io
      path: prplanit/stagefreight
      tags:
        - "{version}"          # 0.2.0
        - "{major}.{minor}"    # 0.2
        - "{major}"            # 0
        - "latest"
      git_tags: [stable]
      credentials: DOCKER

    # ── Docker Hub: pre-releases (alpha/beta/rc) ────────────────────
    # Version tag only — no rolling tags, no latest.
    - url: docker.io
      path: prplanit/stagefreight
      tags:
        - "{version}"          # 0.2.0-alpha.1
      git_tags: [prerelease]
      credentials: DOCKER

    # ── Docker Hub: dev builds on every commit ───────────────────────
    # Ephemeral builds for testing. No git tag required.
    # Retention keeps last 6 dev tags (sha-tagged only; latest-dev is excluded).
    - url: docker.io
      path: prplanit/stagefreight
      tags:
        - "dev-{sha:8}"               # dev-abc12345
        - "latest-dev"                 # always points to newest dev build
      branches: [main]
      credentials: DOCKER
      retention: 6

gitlab_component:
  spec_files:
    - "templates/stagefreight.yml"
  catalog: true

lint:
  level: full
  exclude:
    - "*.ttf"
    - "*.png"
    - "*.jpg"
    - "*.ico"
    - "*.woff"
    - "*.woff2"
  modules:
    freshness:
      enabled: true
      options:
        cache_ttl: 300
        sources:
          docker_images: true
          docker_tools: true
          go_modules: true
        vulnerability:
          enabled: true
    tabs:
      enabled: true
    secrets:
      enabled: true
    conflicts:
      enabled: true
    filesize:
      enabled: true
    linecount:
      enabled: true
    unicode:
      enabled: true
      options:
        # Unicode / invisible text defense — see docs/Linter.md § Unicode
        # No allowlist needed: banner art is build-generated with escaped
        # string literals (no raw control bytes in source).
        detect_bidi: true
        detect_zero_width: true
        detect_control_ascii: true
