version: 1

badges:
  font: dejavu-sans
  font_size: 11
  items:
    - name: release
      label: release
      color: "#74ecbe"
      output: .stagefreight/badges/release.svg
    - name: build
      label: build
      value: "{env:BUILD_STATUS}"
      color: auto
      font: monofur
      output: .stagefreight/badges/build.svg
    - name: license
      label: license
      value: "AGPL-3.0+"
      color: "#310937"
      font: monofur
      output: .stagefreight/badges/license.svg
    - name: updated
      label: updated
      value: "{env:BUILD_DATE}"
      color: "#236144"
      output: .stagefreight/badges/updated.svg

docker:
  readme:
    description: "Declarative CI/CD CLI — detect, build, scan, and release container images from one manifest"
    link_base: "https://github.com/sofmeright/stagefreight/blob/main"
    badges:
      - alt: release
        file: ".stagefreight/badges/release.svg"
        link: "https://github.com/sofmeright/stagefreight/releases"
      - alt: build
        file: ".stagefreight/badges/build.svg"
        link: "https://github.com/sofmeright/stagefreight/actions"
      - alt: license
        file: ".stagefreight/badges/license.svg"
        link: LICENSE
      - alt: updated
        file: ".stagefreight/badges/updated.svg"
      - alt: pulls
        url: "https://img.shields.io/docker/pulls/prplanit/stagefreight"
        link: "https://hub.docker.com/r/prplanit/stagefreight"

  platforms: [linux/amd64]

  registries:
    # ── Docker Hub: stable releases ─────────────────────────────────
    # Full rolling tag set. Renovate picks up {base} for auto-updates.
    # Only clean semver tags (no prerelease suffix).
    - url: docker.io
      path: prplanit/stagefreight
      tags:
        - "{version}"          # 0.2.0
        - "{major}.{minor}"    # 0.2
        - "{major}"            # 0
        - "latest"
      git_tags: ["^\\d+\\.\\d+\\.\\d+$"]
      credentials: DOCKER

    # ── Docker Hub: pre-releases (alpha/beta/rc) ────────────────────
    # Version tag only — no rolling tags, no latest.
    - url: docker.io
      path: prplanit/stagefreight
      tags:
        - "{version}"          # 0.2.0-alpha.1
      git_tags: ["\\d+\\.\\d+\\.\\d+-.+"]
      credentials: DOCKER

    # ── Docker Hub: dev builds on every commit ───────────────────────
    # Ephemeral builds for testing. No git tag required.
    # Retention keeps last 5 dev tags (sha-tagged only; latest-dev is excluded).
    - url: docker.io
      path: prplanit/stagefreight
      tags:
        - "dev-{sha:8}"               # dev-abc12345
        - "latest-dev"                 # always points to newest dev build
      branches: ["^main$"]
      credentials: DOCKER
      retention: 6

component:
  spec_files:
    - "templates/stagefreight.yml"
    - "templates/component-release.yml"
  readme:
    file: "README.md"
  catalog: true
