version: 1

vars:
  org: prplanit
  repo: stagefreight

sources:
  primary:
    kind: git
    worktree: "."
    url: "https://github.com/{var:org}/{var:repo}"
    default_branch: "main"

policies:
  git_tags:
    stable: "^v?\\d+\\.\\d+\\.\\d+$"
    prerelease: "^v?\\d+\\.\\d+\\.\\d+-.+"
  branches:
    main: "^main$"

builds:
  - id: stagefreight
    kind: docker
    platforms: [linux/amd64]

targets:
  # ── Docker Hub: stable releases ─────────────────────────────────
  # Full rolling tag set. Renovate picks up {base} for auto-updates.
  # Only clean semver tags (no prerelease suffix).
  - id: dockerhub-stable
    kind: registry
    build: stagefreight
    url: docker.io
    provider: docker
    path: "{var:org}/{var:repo}"
    tags:
      - "{version}"          # 0.2.0
      - "{major}.{minor}"    # 0.2
      - "{major}"            # 0
      - "latest"
    when: { git_tags: [stable], events: [tag] }
    credentials: DOCKER

  # ── Docker Hub: pre-releases (alpha/beta/rc) ────────────────────
  # Version tag only — no rolling tags, no latest.
  - id: dockerhub-prerelease
    kind: registry
    build: stagefreight
    url: docker.io
    provider: docker
    path: "{var:org}/{var:repo}"
    tags:
      - "{version}"          # 0.2.0-alpha.1
    when: { git_tags: [prerelease], events: [tag] }
    credentials: DOCKER

  # ── Docker Hub: dev builds on every commit ───────────────────────
  # Ephemeral builds for testing. No git tag required.
  # Retention keeps last 6 dev tags (sha-tagged only; latest-dev is protected).
  - id: dockerhub-dev
    kind: registry
    build: stagefreight
    url: docker.io
    provider: docker
    path: "{var:org}/{var:repo}"
    tags:
      - "dev-{sha:8}"        # dev-abc12345
      - "latest-dev"          # always points to newest dev build
    when: { branches: [main], events: [push] }
    credentials: DOCKER
    retention:
      keep_last: 6
      protect: ["latest-dev"]

  # ── Docker Hub: README sync ──────────────────────────────────────
  - id: dockerhub-readme
    kind: docker-readme
    url: docker.io
    path: "{var:org}/{var:repo}"
    credentials: DOCKER
    when: { branches: [main], events: [push, tag] }
    file: "README.md"
    description: "Declarative CI/CD CLI — detect, build, scan, and release container images from one manifest"
    link_base: "https://github.com/{var:org}/{var:repo}/blob/main"

  # ── GitLab component catalog ─────────────────────────────────────
  - id: gitlab-catalog
    kind: gitlab-component
    when: { branches: [main], events: [push] }
    spec_files: ["templates/stagefreight.yml"]
    catalog: true

  # ── Primary release (rolling git tag aliases) ────────────────────
  - id: primary-release
    kind: release
    aliases: ["{version}", "{major}.{minor}", "latest"]
    when: { git_tags: [stable], events: [tag] }

narrator:
  - file: "README.md"
    link_base: "https://github.com/{var:org}/{var:repo}/blob/main"
    items:
      - id: badge.release
        kind: badge
        placement:
          between: ["<!-- sf:badges:start -->", "<!-- sf:badges:end -->"]
          mode: replace
          inline: true
        text: release
        color: "#74ecbe"
        font: dejavu-sans
        font_size: 11
        output: ".stagefreight/badges/release.svg"
        link: "https://github.com/{var:org}/{var:repo}/releases"

      - id: badge.build
        kind: badge
        placement:
          between: ["<!-- sf:badges:start -->", "<!-- sf:badges:end -->"]
          mode: replace
          inline: true
        text: build
        value: "{env:BUILD_STATUS}"
        color: auto
        font: monofur
        output: ".stagefreight/badges/build.svg"
        link: "https://github.com/{var:org}/{var:repo}/actions"

      - id: badge.license
        kind: badge
        placement:
          between: ["<!-- sf:badges:start -->", "<!-- sf:badges:end -->"]
          mode: replace
          inline: true
        text: license
        value: "AGPL-3.0+"
        color: "#310937"
        font: monofur
        output: ".stagefreight/badges/license.svg"
        link: LICENSE

      - id: badge.updated
        kind: badge
        placement:
          between: ["<!-- sf:badges:start -->", "<!-- sf:badges:end -->"]
          mode: replace
          inline: true
        text: updated
        value: "{env:BUILD_DATE}"
        color: "#236144"
        font: dejavu-sans
        font_size: 11
        output: ".stagefreight/badges/updated.svg"

      - id: shield.pulls
        kind: shield
        placement:
          between: ["<!-- sf:badges:start -->", "<!-- sf:badges:end -->"]
          mode: replace
          inline: true
        shield: "docker/pulls/{var:org}/{var:repo}"
        link: "https://hub.docker.com/r/{var:org}/{var:repo}"

  - file: "docs/Component.md"
    items:
      - id: component-docs
        kind: component
        placement:
          between: ["<!-- sf:component:start -->", "<!-- sf:component:end -->"]
          mode: replace
        spec: "templates/stagefreight.yml"

lint:
  level: full
  exclude:
    - "*.ttf"
    - "*.png"
    - "*.jpg"
    - "*.ico"
    - "*.woff"
    - "*.woff2"
  modules:
    freshness:
      enabled: true
      options:
        cache_ttl: 300
        sources:
          docker_images: true
          docker_tools: true
          go_modules: true
        vulnerability:
          enabled: true
    tabs:
      enabled: true
    secrets:
      enabled: true
    conflicts:
      enabled: true
    filesize:
      enabled: true
    unicode:
      enabled: true
      options:
        # Unicode / invisible text defense — see docs/Linter.md § Unicode
        # No allowlist needed: banner art is build-generated with escaped
        # string literals (no raw control bytes in source).
        detect_bidi: true
        detect_zero_width: true
        detect_control_ascii: true

security:
  enabled: true
  sbom: true
