package narrator

// ComponentModule renders pre-generated component documentation markdown.
// The spec file is parsed and docs generated by the caller; this module
// just carries the rendered output into the narrator composition pipeline.
type ComponentModule struct {
	Docs string // pre-rendered markdown from component.GenerateDocs
}

// Render returns the component documentation as-is.
func (c ComponentModule) Render() string {
	return c.Docs
}
