spec:
  inputs:
    # input_section_name- StageFreight Settings
    # input_section_desc- Core settings for the component release pipeline.
    stagefreight_image:
      description: "StageFreight image to use"
      type: string
      default: "docker.io/prplanit/stagefreight:latest"
    # input_section_name- Component Documentation
    # input_section_desc- Controls input documentation generation and README injection.
    readme_file:
      description: "README file to inject component input docs into"
      type: string
      default: "README.md"
    commit_docs:
      description: "Commit updated README via forge API"
      type: boolean
      default: true
    commit_branch:
      description: "Branch to commit updated README to"
      type: string
      default: "main"
    # input_section_name- Release Settings
    # input_section_desc- Controls release creation and badge updates.
    release_enabled:
      description: "Create a release on the forge"
      type: boolean
      default: true
    catalog_links:
      description: "Add GitLab Catalog link to the release"
      type: boolean
      default: true

---

stages:
  - docs
  - release

generate-docs:
  stage: docs
  image: $[[ inputs.stagefreight_image ]]
  variables:
    GIT_DEPTH: 0
  script:
    - stagefreight component docs --readme $[[ inputs.readme_file ]] --commit --branch $[[ inputs.commit_branch ]]
  rules:
    - if: '$CI_COMMIT_TAG && $[[ inputs.commit_docs ]]'
      when: always
    - when: never

create-release:
  stage: release
  image: $[[ inputs.stagefreight_image ]]
  variables:
    GIT_DEPTH: 0
  needs:
    - job: generate-docs
      optional: true
  script:
    - stagefreight release create --catalog-links=$[[ inputs.catalog_links ]]
    - stagefreight release badge
  rules:
    - if: '$CI_COMMIT_TAG && $[[ inputs.release_enabled ]]'
      when: always
    - when: never
