spec:
  inputs:
    stagefreight_image:
      description: "StageFreight image to use for the build"
      type: string
      default: "docker.io/prplanit/stagefreight:latest"
    dind_image:
      description: "Docker-in-Docker service image"
      type: string
      default: "docker.io/docker:27-dind"
    stagefreight_args:
      description: "Additional arguments passed to stagefreight docker build"
      type: string
      default: ""
    security_scan:
      description: "Run security scan after build"
      type: boolean
      default: true
    security_detail:
      description: "Security detail level for release notes (none, counts, detailed, full)"
      type: string
      default: "counts"
    release_enabled:
      description: "Create a release on the forge after build"
      type: boolean
      default: true

---

stages:
  - build
  - security
  - release

build-image:
  stage: build
  image: $[[ inputs.stagefreight_image ]]
  services:
    - name: $[[ inputs.dind_image ]]
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
  artifacts:
    paths:
      - .stagefreight/
    expire_in: 2 hours
  before_script:
    - docker context create tls-context --docker "host=$DOCKER_HOST,ca=$DOCKER_CERT_PATH/ca.pem,cert=$DOCKER_CERT_PATH/cert.pem,key=$DOCKER_CERT_PATH/key.pem"
    - docker buildx create --name stagefreight-builder --use tls-context
  script:
    - stagefreight docker build $[[ inputs.stagefreight_args ]]
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always

security-scan:
  stage: security
  image: $[[ inputs.stagefreight_image ]]
  needs: [build-image]
  services:
    - name: $[[ inputs.dind_image ]]
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_CERTDIR: "/certs"
  artifacts:
    paths:
      - .stagefreight/security/
    expire_in: 1 week
  before_script:
    - docker context create tls-context --docker "host=$DOCKER_HOST,ca=$DOCKER_CERT_PATH/ca.pem,cert=$DOCKER_CERT_PATH/cert.pem,key=$DOCKER_CERT_PATH/key.pem"
    - docker buildx create --name security-scanner --use tls-context
  script:
    - stagefreight security scan --output .stagefreight/security/ --security-detail $[[ inputs.security_detail ]]
  rules:
    - if: '$CI_COMMIT_TAG && $[[ inputs.security_scan ]]'
      when: always
    - when: never

create-release:
  stage: release
  image: $[[ inputs.stagefreight_image ]]
  needs:
    - build-image
    - job: security-scan
      optional: true
  script:
    - stagefreight release create --security-summary .stagefreight/security/ --registry-links
    - stagefreight release badge
  rules:
    - if: '$CI_COMMIT_TAG && $[[ inputs.release_enabled ]]'
      when: always
    - when: never
